// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);

		double lessThenHalf = 0; 
		double moreThanHalf =0;
		double ratio = 0;
		

		for ( int i = 0; i < n; i++){
			
			if  (Math.random() > 0.5) 
			{
				moreThanHalf++;
			}
			 else
			{
				lessThenHalf++;
			}

		}

		if (moreThanHalf > lessThenHalf){
			ratio = lessThenHalf/moreThanHalf;
		} else { 
			ratio = moreThanHalf/lessThenHalf;
		}

		System.out.println("> 0.5: " + (int)moreThanHalf);

		System.out.println("<= 0.5: " +(int)lessThenHalf);

		System.out.println("Ratio: " + ratio);
			
		}
	}
	/*% java TestRandom 100
> 0.5: 47 times
<= 0.5: 53 times
Ratio: 0.8867924528301887
% java TestRandom 10000
> 0.5: 4986 times
<= 0.5: 5014 times
Ratio: 0.994415636218588
% java TestRandom 3
> 0.5: 3 times
<= 0.5: 0 times */

